#端口号
server:
  port: 8088

#数据源
spring:
  datasource:
    jdbc-url: 'jdbc:mysql://localhost/blog?useUnicode=true&characterEncoding=UTF-8&useSSL=true&autoReconnect=true'
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver

  #JPA设置
  jpa:
    show-sql: true
    open-in-view: true
    properties:
      hibernate:
        hbm2ddl.auto: update
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        format_sql: true
#        search.default.directory_provider: filesystem
#        search.default.indexBase: ${search.default.indexBase:/var/hais/lucene/indexes/}
## rabbit mq properties
rabbitmq:
  host: localhost
  port: 5672
  username: guest
  password: guest

logging.level:
  root: info
  org.springframework: INFO
  com.ajmd: debug
#日志输出路径
logging.path: C:/logs/blog



